Biblioteca/Biblioteca/Controllers/NoticiaController.cs
using Biblioteca.DBContext;
using Biblioteca.DTOS;
using Biblioteca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.Controllers
{
    public class NoticiaController : Controller
    {
        private ApplicationDBContext bd;
        // GET: Noticias
        public ActionResult Index()
        {
            var carruselDTO = new List<CarruselDTO>();

            using (bd = new ApplicationDBContext())
            {
                carruselDTO = (from c in bd.Carrusel
                               select new CarruselDTO
                               {
                                   ID = c.ID,
                                   ImagePath = c.ImagePath,
                                   Nombre = c.Nombre,
                                   Descripcion = c.Descripcion,
                                   Url = c.Url
                               }).ToList();
            }


            return View(carruselDTO);
        }

        [HttpGet]
        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(CarruselDTO carruselDTO)
        {
            using (bd = new ApplicationDBContext())
            {
                Carrusel carrusel = new Carrusel()
                {
                    ID = carruselDTO.ID,
                    ImagePath = carruselDTO.ImagePath,
                    Nombre = carruselDTO.Nombre,
                    Descripcion = carruselDTO.Descripcion,
                    Url = carruselDTO.Url
                };

                bd.Carrusel.Add(carrusel);
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Editar(int id)
        {
            CarruselDTO carruselDTO = new CarruselDTO();

            using (bd = new ApplicationDBContext())
            {
                Carrusel carrusel = bd.Carrusel.Where(i => i.ID.Equals(id)).First();

                carruselDTO = new CarruselDTO()
                {
                    ID = carrusel.ID,
                    Nombre = carruselDTO.Nombre
                };
            }

            return View(carruselDTO);
        }


        [HttpPost]
        public ActionResult Editar(CarruselDTO carruselDTO)
        {
            if (!ModelState.IsValid)
            {
                return View(carruselDTO);
            }

            using (bd = new ApplicationDBContext())
            {
                Carrusel carrusel = bd.Carrusel.Where(i => i.ID.Equals(carruselDTO.ID)).First();

                carrusel.Descripcion = carruselDTO.Descripcion;
                carrusel.Nombre = carruselDTO.Nombre;
                carrusel.ImagePath = carruselDTO.ImagePath;
                carrusel.Url = carruselDTO.Url;

                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int id)
        {
            using (bd = new ApplicationDBContext())
            {
                Carrusel carrusel = bd.Carrusel.Where(c => c.ID.Equals(id)).First();

                bd.Carrusel.Remove(carrusel);
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }


    }
}

Biblioteca/Biblioteca/Views/Noticia/Agregar.cshtml
@using Biblioteca.DTOS
@model CarruselDTO

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar</h>
    <div class="row">
        <div class="col.md-6">
            @using (@Html.BeginForm("Agregar", "Noticia", FormMethod.Post, new { @id = "frmAgregar", @enctype = "multipart/form-data" }))
            {
                <div>
                    @Html.LabelFor(p => p.ImagePath)
                    @Html.TextBoxFor(p => p.ImagePath, new { @class = "form-control" })
                    @Html.ValidationMessage("Imagen", new { @class = "text-danger" })
                </div>

                <div>
                    @Html.LabelFor(p => p.Nombre)
                    @Html.TextBoxFor(p => p.Nombre, new { @class = "form-control" })
                    @Html.ValidationMessage("Nombre", new { @class = "text-danger" })
                </div>

                //Poner un textarea
                //VerificationAttribute porque salen tan grandes la letras
                <div>
                    @Html.LabelFor(p => p.Descripcion)
                    @Html.TextBoxFor(p => p.Descripcion, new { @class = "form-control" })
                    @Html.ValidationMessage("Descripcion", new { @class = "text-danger" })
                </div>

                <div>
                    @Html.LabelFor(p => p.Url)
                    @Html.TextBoxFor(p => p.Url, new { @class = "form-control" })
                    @Html.ValidationMessage("Url", new { @class = "text-danger" })
                </div>

                <br />
                <div style="margin:auto;">
                    <button type="submit" class="btn btn-primary" , Onclick="agregar()">
                        Guardar
                    </button>
                    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-danger", @Onclick = "regresar()" })
                </div>
            }
        </div>

        <script>
            function agregar() {
                if (confirm("¿Deseas guardar los cambios?")) {
                    //alert("Nuevo usuario registrado");
                } else {
                    event.preventDefault();
                }
            }

            function regresar() {
                if (confirm("¿Desea cancelar los cambios?") == 1) {
                    alert("Usuario no registrado");
                } else {
                    event.preventDefault();
                }
            }

            let imgFoto = document.getElementById("imgFoto");
            let fupFoto = document.getElementById("fupFoto");
            fupFoto.onchange = function () {
                let files = fupFoto.files[0];
                let reader = new FileReader();
                reader.onloadend = function () {
                    imgFoto.src = reader.result;
                    document.getElementById("nombreFoto").value = file.name;
                }

                reader.readAsDataURL(files);
            }

        </script>

Biblioteca/Biblioteca/Views/Noticia/Editar.cshtml
@using Biblioteca.DTOS
@model CarruselDTO

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Noticia</h2>
<div class="row">
<div class="col-md-6">
    @*Accion   Controlador metodo *@
    @using (Html.BeginForm("Editar", "Noticia", FormMethod.Post, new { @id = "frmEditar" }))
    {

        <div>
            @Html.LabelFor(p => p.ID)
            @Html.TextBoxFor(p => p.ID, new { @class = "form-control", @readOnly = true })
        </div>

        <div style="margin-bottom:10px;">
            @Html.LabelFor(p => p.ImagePath)
            @Html.TextBoxFor(p => p.ImagePath, new { @class = "form-control" })
            @Html.ValidationMessage("ImagenPath", new { @class = "text-danger" })
        </div>

        <div style="margin-bottom:10px;">
            @Html.LabelFor(p => p.Nombre)
            @Html.TextBoxFor(p => p.Nombre, new { @class = "form-control" })
            @Html.ValidationMessage("Nombre", new { @class = "text-danger" })
        </div>

        <div style="margin-bottom:10px;">
            @Html.LabelFor(p => p.Descripcion)
            @Html.TextBoxFor(p => p.Descripcion, new { @class = "form-control" })
            @Html.ValidationMessage("Descripción", new { @class = "text-danger" })
        </div>

        <div style="margin-bottom:10px;">
            @Html.LabelFor(p => p.Url)
            @Html.TextBoxFor(p => p.Url, new { @class = "form-control" })
            @Html.ValidationMessage("Url", new { @class = "text-danger" })
        </div>

        <br />
        <div style="margin:auto;">
            <button type="submit" class="btn btn-primary" onclick="editar()">
                Guardar
            </button>
            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-danger", @Onclick = "regresar()" })
        </div>
    }
</div>
</div>

<script>
    function editar() {
        if (confirm("¿Deseas guardar los cambios?")) {
            alert("Informacion editada");
        } else {
            event.preventDefault();
        }
    }

    function regresar() {
        if (confirm("¿Desea cancelar los cambios?") == 1) {
            alert("Cambios no guardados");
        } else {
            event.preventDefault();
        }
    }
</script>

Biblioteca/Biblioteca/Views/Noticia/Index.cshtml
@using Biblioteca.DTOS

@model IEnumerable<CarruselDTO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-5">Noticias</h2>

<p>
    @Html.ActionLink("Nueva Noticia", "Agregar", "Noticia", null, new { @class = "btn btn-primary" })
</p>
@using (Html.BeginForm("Index", "Carrusel", FormMethod.Post, new { @id = "frmCarrusel" }))
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th>
                Operaciones
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ImagePath)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Url)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", "Noticia", new { id = @item.ID }, new { @class = "glyphicon glyphicon-pencil btn btn-primary", @Onclick = "editar()" })

                    @Html.ActionLink(" Eliminar", "Eliminar", "Noticia", new { id = @item.ID }, new { @class = "glyphicon glyphicon-trash btn btn-danger mt-3", @Onclick = "eliminar()" })
                </td>
            </tr>
        }

    </table>
}