Biblioteca/Biblioteca/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Biblioteca.Models
{
    public class Categoria
    {
        public int ID { get; set; }
        public string Nombre_Categoria { get; set; }
        public int C_habilitado { get; set; }
    }
}

Biblioteca/Biblioteca/Controllers/CategoriaController.cs
using Biblioteca.DBContext;
using Biblioteca.DTOS;
using Biblioteca.Filters;
using Biblioteca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.Controllers
{
    [Admin]
    public class CategoriaController : Controller
    {
        private ApplicationDBContext bd;
        // GET: Categoria
        public ActionResult Index(CategoriaDTO categoriaDTO)
        {
            List<CategoriaDTO> categorias = null;
            string nombreCategoria = categoriaDTO.Nombre_Categoria;

            using (bd = new ApplicationDBContext())
            {
                if (nombreCategoria != null)
                {
                    categorias = (from c in bd.Categorias
                                  where c.C_habilitado == 1
                                  && c.Nombre_Categoria.Contains(nombreCategoria)
                                  select new CategoriaDTO
                                  {
                                      ID = c.ID,
                                      Nombre_Categoria = c.Nombre_Categoria
                                  }).ToList();
                }
                else
                {
                    categorias = (from c in bd.Categorias
                                  where c.C_habilitado == 1
                                  select new CategoriaDTO
                                  {
                                      ID = c.ID,
                                      Nombre_Categoria = c.Nombre_Categoria
                                  }).ToList();
                }

            }

            return View(categorias);
        }

        [HttpGet]
        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(CategoriaDTO categoriaDTO)
        {

            int categorias = 0;

            using (bd = new ApplicationDBContext())
            {
                categorias = bd.Categorias.Where(c => c.Nombre_Categoria.Equals(categoriaDTO.Nombre_Categoria)).Count();
            }


            if (!ModelState.IsValid || categorias >= 1)
            {
                if (categorias >= 1)
                {
                    categoriaDTO.mensaje = "La categoria ya existe";
                }

                return View(categoriaDTO);
            }

            using (bd = new ApplicationDBContext())
            {
                Categoria categoria = new Categoria()
                {
                    ID = categoriaDTO.ID,
                    Nombre_Categoria = categoriaDTO.Nombre_Categoria,
                    C_habilitado = 1
                };

                bd.Categorias.Add(categoria);
                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            CategoriaDTO categoriaDTO = null;

            using (bd = new ApplicationDBContext())
            {
                Categoria categoria = bd.Categorias.Where(i => i.ID.Equals(id)).First();

                categoriaDTO = new CategoriaDTO()
                {
                    ID = categoria.ID,
                    Nombre_Categoria = categoria.Nombre_Categoria
                };

            }

            return View(categoriaDTO);
        }

        [HttpPost]
        public ActionResult Editar(CategoriaDTO categoriaDTO)
        {
            if (!ModelState.IsValid)
            {
                return View(categoriaDTO);
            }

            using (bd = new ApplicationDBContext())
            {
                Categoria categoria = bd.Categorias.Where(i => i.ID.Equals(categoriaDTO.ID)).First();

                categoria.ID = categoriaDTO.ID;
                categoria.Nombre_Categoria = categoriaDTO.Nombre_Categoria;

                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int id)
        {
            using (bd = new ApplicationDBContext())
            {
                Categoria categoria = bd.Categorias.Where(c => c.ID.Equals(id)).First();

                categoria.C_habilitado = 0;

                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Biblioteca/Biblioteca/Views/Categoria/Agregar.cshtml
@using Biblioteca.DTOS
@model CategoriaDTO
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar categoria</h2>

<div class="row">
    <div class="col-md-6">
        @*Accion   Controlador metodo *@
        @using (@Html.BeginForm("Agregar", "Categoria", FormMethod.Post, new { @id = "frmEditar" }))
        {

            <div style="margin-bottom:10px;">
                @Html.LabelFor(p => p.Nombre_Categoria)
                @Html.TextBoxFor(p => p.Nombre_Categoria, new { @class = "form-control" })
                @Html.ValidationMessage("Nombre_Categoria", new { @class = "text-danger" })

                @if (Model != null && Model.mensaje != null)
                {
                    @Html.Label(Model.mensaje, new { @class = "text-danger", @id = "msjError" })
                }
            </div>

            <br />
            <div style="margin:auto;">
                <button type="submit" class="btn btn-primary" onclick="confirmar()">
                    Guardar
                </button>
                @Html.ActionLink("Regresar", "Index", "Categoria", null, new { @class = "btn btn-danger", @Onclick = "regresar()" })
            </div>

        }
    </div>
</div>

<script>


    function confirmar() {
        if (confirm("¿Desea guardar los cambios?") == 1) {
        } else {
            event.preventDefault();
        }
    }

    function regresar() {
        if (confirm("¿Desea cancelar los cambios?") == 1) {
            alert("Categoria no registrada");
        } else {
            event.preventDefault();
        }
    }
</script>

Biblioteca/Biblioteca/Views/Categoria/Editar.cshtml
@using Biblioteca.DTOS
@model CategoriaDTO
@{
    ViewBag.Title = "Editar";
}

<h2>Editar categoria</h2>

<div class="row">
    <div class="col-md-6">
        @*Accion   Controlador metodo *@
        @using (@Html.BeginForm("Editar", "Categoria", FormMethod.Post, new { @id = "frmEditar" }))
        {

            <div>
                @Html.LabelFor(p => p.ID)
                @Html.TextBoxFor(p => p.ID, new { @class = "form-control", @readOnly = true })
            </div>

            <div style="margin-bottom:10px;">
                @Html.LabelFor(p => p.Nombre_Categoria)
                @Html.TextBoxFor(p => p.Nombre_Categoria, new { @class = "form-control" })
                @Html.ValidationMessage("Nombre_Categoria", new { @class = "text-danger" })
            </div>

            <br />
            <div style="margin:auto;">
                <button type="submit" class="btn btn-primary" , onclick="editar()">
                    Guardar
                </button>
                @Html.ActionLink("Regresar", "Index", "Categoria", null, new { @class = "btn btn-danger", @Onclick = "regresar()" })
            </div>
        }
    </div>
</div>

<script>
    function editar() {
        if (confirm("¿Deseas guardar los cambios?")) {
            alert("Informacion editada");
        } else {
            event.preventDefault();
        }
    }

    function regresar() {
        if (confirm("¿Desea cancelar los cambios?") == 1) {
            alert("Cambios no guardados");
        } else {
            event.preventDefault();
        }
    }
</script>

Biblioteca/Biblioteca/Views/Categoria/Index.cshtml
@using Biblioteca.DTOS
@model IEnumerable<CategoriaDTO>
@{
    ViewBag.Title = "Index";
}



<h2 class="mt-5">Categorias de libros actuales</h2>

<p>
    @Html.ActionLink("Agregar", "Agregar", "Categoria", null, new { @class = "btn btn-primary" })
</p>

@using (Html.BeginForm("Index", "Categoria", FormMethod.Post, new { @id = "frmCategoria" }))
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_Categoria)
            </th>
            <th>
                Operaciones
            </th>
        </tr>

        <tr>
            <td></td>
            <td>@Html.TextBox("Nombre_Categoria", null, new { @class = "form-control" })</td>
            <td></td>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre_Categoria)
                </td>


                <td>
                    @Html.ActionLink("Editar", "Editar", "Categoria", new { id = @item.ID }, new { @class = "glyphicon glyphicon-pencil btn btn-primary", @onclick = "editar()" })

                    @Html.ActionLink("Eliminar", "Eliminar", "Categoria", new { id = @item.ID }, new { @class = "glyphicon glyphicon-trash btn btn-danger", @onclick = "eliminar()" })
                </td>
            </tr>
        }

    </table>
}

<script>

    let frmCategoria = document.getElementById("frmCategoria")
    let Nombre_Categoria = document.getElementById("Nombre_Categoria");

    Nombre_Categoria.onkeyup = function () {
        frmCategoria.submit();
    }

    function editar() {
        if (confirm("¿Desea editar el registro?") == 1) {
        } else {
            event.preventDefault();
        }
    }

    function eliminar() {
        if (confirm("¿Desea eliminar el registro?") == 1) {
            alert("Se elimino correctamente");
        } else {
            event.preventDefault();
        }
    }

</script>