Biblioteca/Biblioteca/Models/Sugerencia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Biblioteca.Models
{
    public class Sugerencia
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Comentario { get; set; }

        

    }
}

Biblioteca/Biblioteca/Controllers/SugerenciaController.cs
using Biblioteca.DBContext;
using Biblioteca.DTOS;
using Biblioteca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.Controllers
{
    public class SugerenciaController : Controller
    {
        private ApplicationDBContext bd;

        // GET: Sugerencias
        public ActionResult Index()
        {
            var sugerenciaDTO = new List<SugerenciaDTO>();
            using (bd = new ApplicationDBContext())
            {
                sugerenciaDTO = (from s in bd.Sugerencia
                                 select new SugerenciaDTO
                                 {
                                     ID = s.ID,
                                     Nombre = s.Nombre,
                                     Email = s.Email,
                                     Comentario = s.Comentario
                                 }).ToList();
            }
            return View(sugerenciaDTO);
        }

        public ActionResult Eliminar(int id)
        {
            using (bd = new ApplicationDBContext())
            {
                Sugerencia sugerencia = (from s in bd.Sugerencia
                                         where s.ID == id
                                         select s).FirstOrDefault();

                bd.Sugerencia.Remove(sugerencia);

                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }

    }
}

Biblioteca/Biblioteca/Views/Sugerencia/Index.cshtml
@using Biblioteca.DTOS 
@model IEnumerable<SugerenciaDTO>

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2 class="mt-5">Sugerencias</h2>

    @using (Html.BeginForm("Index", "Sugerencia", FormMethod.Post, new { @id = "frmSugerencia" }))
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Comentario)
                </th>
                <th>
                    Operación
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @Html.DisplayFor(modelitem => item.Nombre)
                    </th>
                    <th>
                        @Html.DisplayFor(modelitem => item.Email)
                    </th>
                    <th>
                        @Html.DisplayFor(modelitem => item.Comentario)
                    </th>
                    <th>
                        @Html.ActionLink("Eliminar", "Eliminar", "Sugerencia", new { id = @item.ID }, new { @class = "glyphicon glyphicon-trash btn btn-danger", @Onclick = "eliminar()" })
                    </th>
                </tr>
            }
        </table>
    }

<script>
    function eliminar() {
        if (confirm("¿Desea eliminar el registro?") == 1) {
            
        } else {
            event.preventDefault();
        }
    }
</script>