Biblioteca/Biblioteca/Controllers/LibroController.cs
using Biblioteca.DBContext;
using Biblioteca.DTOS;
using Biblioteca.Filters;
using Biblioteca.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.Controllers
{
    //[Admin]
    public class LibroController : Controller
    {
        private ApplicationDBContext bd;
        private LibroDTO libroDTOVal;
        // GET: Libro
        public ActionResult Index(LibroDTO libroDTO)
        {
            List<LibroDTO> libros = null;
            List<LibroDTO> librosFiltrados = null;
            libroDTOVal = libroDTO;
            using (bd = new ApplicationDBContext())
            {
                libros = (from l in bd.Libros
                          join c in bd.Categorias
                          on l.IDCategoria equals c.ID
                          where l.L_Habilitado == 1
                          select new LibroDTO
                          {
                              ID = l.ID,
                              Nombre_Autor = l.Nombre_Autor,
                              Titulo = l.Titulo,
                              Cantidad = l.Cantidad,
                              Anio_Publicacion = l.Anio_Publicacion,
                              lenguaje = l.Idioma,
                              categoria_Libro = c.Nombre_Categoria,
                              Disponibles = l.Total_Actual.ToString() + "/" + l.Cantidad.ToString(),
                              Fecha_Registro = l.Fecha_Registro,
                              Ubicacion = l.Ubicacion,
                              Edicion = l.Edicion
                          }).ToList();

                if (libroDTO.Titulo == null && libroDTO.Nombre_Autor == null && libroDTO.lenguaje == null && libroDTO.categoria_Libro == null)
                {
                    librosFiltrados = libros;
                }
                else
                {
                    Predicate<LibroDTO> prediTitulo = new Predicate<LibroDTO>(buscarLibro);
                    librosFiltrados = libros.FindAll(prediTitulo);
                }
            }

            return View(librosFiltrados);
        }

        [HttpGet]
        public ActionResult Agregar()
        {
            listarCategorias();
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(LibroDTO libro, HttpPostedFileBase foto, HttpPostedFileBase PDF)
        {
            try
            {
                int registros = 0;
                int registrosEstante = 0;
                using (bd = new ApplicationDBContext())
                {
                    registros = bd.Libros.Where(l => l.Titulo.Equals(libro.Titulo)
                                            && l.Edicion.Equals(libro.Edicion)
                                            && l.Idioma.Equals(libro.lenguaje)).Count();

                    registrosEstante = bd.Libros.Where(l => l.Ubicacion.Equals(libro.Ubicacion)).Count();
                }

                if (!ModelState.IsValid || registros >= 1 || registrosEstante >= 1 || foto == null || PDF == null)
                {
                    if (registros >= 1)
                    {
                        libro.mensaje = "El libro ya existe";
                    }

                    if (registrosEstante >= 1)
                    {
                        libro.mensajeEstante = "Ya hay un libro en esa ubicación";
                    }

                    //Verificar la foto
                    if (foto == null)
                    {
                        libro.mensaje = "La imagen de la portada es obligatoria";
                    }

                    if (PDF == null)
                    {
                        libro.mensaje = "El indice en PDF es obligatorio";
                    }

                    listarCategorias();
                    return View(libro);
                }

                //imagen de la portada


                using (bd = new ApplicationDBContext())
                {
                    Libro l = new Libro();

                    #region Imagen y PDF
                    BinaryReader lector = new BinaryReader(foto.InputStream);
                    byte[] fotoBD = lector.ReadBytes((int)foto.ContentLength);

                    BinaryReader reader = new BinaryReader(PDF.InputStream);
                    byte[] pdfBD = reader.ReadBytes((int)PDF.ContentLength);
                    #endregion

                    l.ID = libro.ID;
                    l.Nombre_Autor = libro.Nombre_Autor;
                    l.Titulo = libro.Titulo;
                    l.Ubicacion = libro.Ubicacion;
                    l.IDCategoria = libro.IDCategoria;
                    l.Edicion = libro.Edicion;
                    l.Cantidad = libro.Cantidad;
                    l.Total_Actual = libro.Cantidad;
                    l.Idioma = libro.lenguaje;
                    l.Fecha_Registro = DateTime.Now;
                    l.Anio_Publicacion = libro.Anio_Publicacion;
                    l.img = fotoBD;
                    l.NombreImg = foto.FileName;
                    l.NombrePDF = PDF.FileName;
                    l.PDF = pdfBD;
                    l.L_Habilitado = 1;

                    bd.Libros.Add(l);
                    bd.SaveChanges();
                }
            }
            catch (Exception e)
            {

            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            listarCategorias();

            LibroDTO libroDTO = new LibroDTO();

            using (bd = new ApplicationDBContext())
            {
                Libro libro = bd.Libros.Where(l => l.ID.Equals(id)).FirstOrDefault();

                libroDTO.ID = libro.ID;
                libroDTO.Titulo = libro.Titulo;
                libroDTO.Nombre_Autor = libro.Nombre_Autor;
                libroDTO.IDCategoria = libro.IDCategoria;
                libroDTO.Fecha_Registro = libro.Fecha_Registro;
                libroDTO.Cantidad = libro.Cantidad;
                libroDTO.Anio_Publicacion = libro.Anio_Publicacion;
                libroDTO.Edicion = libro.Edicion;
                libroDTO.Ubicacion = libro.Ubicacion;
            }

            return View(libroDTO);
        }

        [HttpPost]
        public ActionResult Editar(LibroDTO libroDTO)
        {
            if (!ModelState.IsValid)
            {
                listarCategorias();
                return View(libroDTO);
            }

            using (bd = new ApplicationDBContext())
            {
                Libro libro = bd.Libros.Where(l => l.ID.Equals(libroDTO.ID)).First();

                libro.ID = libroDTO.ID;
                libro.Titulo = libroDTO.Titulo;
                libro.Nombre_Autor = libroDTO.Nombre_Autor;
                libro.IDCategoria = libroDTO.IDCategoria;
                libro.Fecha_Registro = libroDTO.Fecha_Registro;
                libro.Cantidad = libroDTO.Cantidad;
                libro.Anio_Publicacion = libroDTO.Anio_Publicacion;
                libro.Edicion = libroDTO.Edicion;
                libro.Ubicacion = libroDTO.Ubicacion;

                bd.SaveChanges();

            }

            return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int id)
        {
            using (bd = new ApplicationDBContext())
            {
                Libro libro = bd.Libros.Where(l => l.ID.Equals(id)).First();
                libro.L_Habilitado = 0;

                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Filtro de busqueda avanzada
        /// </summary>
        /// <returns>Regresa la vista del filtro de busqueda avanzada</returns>

        [HttpGet]
        public ActionResult BusquedaAvanzada()
        {
            List<LibroDTO> libro = new List<LibroDTO>();
            return View(libro);
        }

        
        /// <summary>
        /// Filtro para realizar busquedas avanzadas
        /// Recibe una o más de las siguientes propiedades del objeto
        /// </summary>
        /// <param name="libroDTO">Este es el objeto</param>
        /// <param name="nombreAutor"></param>
        /// <param name="tituloLibro"></param>
        /// <param name="añoPublicación"></param>
        /// <param name="edicion"></param>
        /// <param name="idioma"></param>
        /// <returns>Regresa un libro que coincida con la busqueda</returns>

        [HttpPost]
        public ActionResult BusquedaAvanzada(LibroDTO libroDTO)
        {
            List<LibroDTO> libros = null;
            List<LibroDTO> librosFiltrados = null;
            libroDTOVal = libroDTO;
            using (bd = new ApplicationDBContext())
            {
                libros = (from l in bd.Libros
                          join c in bd.Categorias
                          on l.IDCategoria equals c.ID
                          where l.L_Habilitado == 1
                          select new LibroDTO
                          {
                              ID = l.ID,
                              Nombre_Autor = l.Nombre_Autor,
                              Titulo = l.Titulo,
                              Cantidad = l.Cantidad,
                              Anio_Publicacion = l.Anio_Publicacion,
                              lenguaje = l.Idioma,
                              categoria_Libro = c.Nombre_Categoria,
                              Disponibles = l.Total_Actual.ToString() + "/" + l.Cantidad.ToString(),
                              Fecha_Registro = l.Fecha_Registro,
                              Ubicacion = l.Ubicacion,
                              Edicion = l.Edicion
                          }).ToList();

                if (libroDTO.Titulo == null && libroDTO.Nombre_Autor == null && libroDTO.lenguaje == null

Biblioteca/Biblioteca/Controllers/LoginController.cs
using Biblioteca.DBContext;
using Biblioteca.DTOS;
using Biblioteca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.Controllers
{
    public class LoginController : Controller
    {
        private ApplicationDBContext bd;
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult Index(UsuarioDTO alumnoDTO)
        {
            string mensaje = "";
            string correo = alumnoDTO.Email;
            string password = alumnoDTO.Password;

            #region Cifrar contraseña
            SHA256Managed sha = new SHA256Managed();
            byte[] byteContra = Encoding.Default.GetBytes(password);
            byte[] byteContraCifrada = sha.ComputeHash(byteContra);
            string passwordCifrado = BitConverter.ToString(byteContraCifrada).Replace("-", "");
            #endregion

            using (bd = new ApplicationDBContext())
            {
                int habilitado = bd.Usuarios.Where(a => a.U_Habilitado == 1 && a.Email.Equals(correo)).Count();
                
                if (habilitado == 0)
                {
                    //Usuario no habilitado
                    alumnoDTO.mensaje = "El Usuario no existe.";
                    return View(alumnoDTO);
                }
                else
                {
                    //Usuario habilitado
                    int numeroVeces = bd.Usuarios.Where(a => a.Email.Equals(correo)
                                     && a.Password.Equals(passwordCifrado)).Count();

                    mensaje = numeroVeces.ToString();

                    if (mensaje.Equals("0"))
                    {
                        //Contraseña incorrecta
                        alumnoDTO.mensaje = "Contraseña incorrecta.";
                        return View(alumnoDTO);
                    }
                    else
                    {
                        //Sesión iniciada 
                        Usuario usuario = bd.Usuarios.Where(a => a.Email.Equals(correo)
                                                  && a.Password.Equals(passwordCifrado)).First();
                        //Buscando el tipo de usuario
                        if (usuario.TipoUsuarioID == 1 || usuario.TipoUsuarioID == 2)
                        {
                            Session["Usuario"] = usuario;
                        }
                        else if (usuario.TipoUsuarioID == 3)
                        {
                            Session["Bibliotecario"] = usuario;
                        }
                        else
                        {
                            UsuarioDTO administrador = (from a in bd.Usuarios
                                                        join u in bd.TipoUsuarios
                                                        on a.TipoUsuarioID equals u.ID
                                                        where a.U_Habilitado == 1
                                                        && u.Tipo_Usuario.Equals("Administrador")
                                                        select new UsuarioDTO
                                                        {
                                                            Nombre = a.Nombre,
                                                            Tipo_Usuario = u.Tipo_Usuario
                                                        }).First();

                            Session["Administrador"] = administrador;
                        }
                    }
                }

                if (!mensaje.Equals("1"))
                {

                    return View(alumnoDTO);
                }
            }

            return RedirectToAction("Index", "Home");
        }//Fin login   

        public ActionResult CerrarSesion()
        {
            if (Session["Usuario"] != null)
            {
                Session["Usuario"] = null;
            }
            else if (Session["Administrador"] != null)
            {
                Session["Administrador"] = null;
            }
            else if (Session["Bibliotecario"] != null)
            {
                Session["Bibliotecario"] = null;
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Perfil()
        {

            if (Session["Usuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var user = (Usuario)Session["Usuario"];
            var nuevoUsuario = new Usuario();
            using (bd = new ApplicationDBContext())
            {
                nuevoUsuario = bd.Usuarios.Where(i => i.ID.Equals(user.ID)).First();
            }
            user = nuevoUsuario;
            UsuarioDTO usuario = new UsuarioDTO
            {
                Direccion = user.Direccion,
                Email = user.Email,
                Fecha_Nacimiento = user.Fecha_Nacimiento,
                ID = user.ID,
                Fecha_Registro = user.Fecha_Registro,
                Nombre = user.Nombre,
                Telefono = user.Telefono


            };

            //tabla de prestamos
            List<PrestamoDTO> prestamos = null;
            var nombreUsuario = usuario.Nombre;
            //consulta para recuperar los prestamos del usuario
            using(bd = new ApplicationDBContext())
            {
                prestamos = (from p in bd.Prestamos
                             join u in bd.Usuarios
                             on p.UsuarioID equals u.ID
                             join l in bd.Libros on p.LibroID equals l.ID
                             where u.Nombre.Contains(nombreUsuario)
                             select new PrestamoDTO
                             {
                                 ID = p.ID,
                                 nombreUsuario = u.Nombre,
                                 tituloLibro = l.Titulo,
                                 Fecha_Devolucion = p.Fecha_Devolucion,
                                 Fecha_Prestamo = p.Fecha_Prestamo

                             }).ToList();
            }
            usuario.prestamos = prestamos;

            return View(usuario);
        }



    }
}

Biblioteca/Biblioteca/Views/Shared/_Layout.cshtml
@using Biblioteca.DTOS
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*nueva barra*@
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        @Html.ActionLink("Libreria digital", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
       
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="mr-3">@Html.ActionLink("Inicio", "Index", "Home", null, new { @class = "text-white" })</li>
                <li class="mr-3">@Html.ActionLink("Buscar", "Index", "Buscar", null, new { @class = "text-white" })</li>
                @if (Session["Administrador"] != null)
                {
                    <li class="mr-3">@Html.ActionLink("Empleados", "Index", "Empleado", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Libros", "Index", "Libro", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Usuarios", "Index", "Usuario", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Categoria", "Index", "Categoria", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Prestamos", "Index", "Prestamo", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Sugerencia", "Index", "Sugerencia", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Noticias", "Index", "Noticia", null, new { @class = "text-white" })</li>
                }
                else if (Session["Bibliotecario"] != null)
                {
                    <li class="mr-3">@Html.ActionLink("Libros", "Index", "Libro", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Categoria", "Index", "Categoria", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Usuarios", "Index", "Usuario", null, new { @class = "text-white" })</li>
                    <li class="mr-3">@Html.ActionLink("Prestamos", "Index", "Prestamo", null, new { @class = "text-white" })</li>
                }

                <li class="mr-3">@Html.ActionLink("Acerca de", "About", "Home", null, new { @class = "text-white" })</li>
                <li class="mr-3">@Html.ActionLink("Contacto", "Contact", "Home", null, new { @class = "text-white" })</li>
                @if (Session["Usuario"] != null)
                {
                    <li class="mr-3">@Html.ActionLink("Perfil", "Perfil", "Login", null, new { @class = "text-white" })</li>
                }
                @*Cerrar sesion*@

                @if (Session["Administrador"] != null || Session["Bibliotecario"] != null || Session["Usuario"] != null)
                {
                    <li class="mr-3">@Html.ActionLink("Cerrar sesión", "CerrarSesion", "Login", null, new { @class = "text-white" })</li>
                    @*<li>@Html.ActionLink("Perfil", "Perfil", "Login")</li>*@
                }
                else
                {
                    <li class="mr-3">@Html.ActionLink("Login", "Index", "Login", null, new { @class = "text-white" })</li>
                }

            </ul>
        </div>
    </nav>
    @*fin nueva barra*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Biblioteca digital</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>